// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/variantlabs/protobuf/l0/user_bonus_received.proto

package events_variantlabs_protobuf_l0

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserBonusReceived struct {
	Uid                  string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ReceivedAtTs         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=received_at_ts,json=receivedAtTs,proto3" json:"received_at_ts,omitempty"`
	Amount               float32                `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserBonusReceived) Reset()         { *m = UserBonusReceived{} }
func (m *UserBonusReceived) String() string { return proto.CompactTextString(m) }
func (*UserBonusReceived) ProtoMessage()    {}
func (*UserBonusReceived) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3faefd792438e, []int{0}
}

func (m *UserBonusReceived) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBonusReceived.Unmarshal(m, b)
}
func (m *UserBonusReceived) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBonusReceived.Marshal(b, m, deterministic)
}
func (m *UserBonusReceived) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBonusReceived.Merge(m, src)
}
func (m *UserBonusReceived) XXX_Size() int {
	return xxx_messageInfo_UserBonusReceived.Size(m)
}
func (m *UserBonusReceived) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBonusReceived.DiscardUnknown(m)
}

var xxx_messageInfo_UserBonusReceived proto.InternalMessageInfo

func (m *UserBonusReceived) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserBonusReceived) GetReceivedAtTs() *timestamppb.Timestamp {
	if m != nil {
		return m.ReceivedAtTs
	}
	return nil
}

func (m *UserBonusReceived) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*UserBonusReceived)(nil), "events.variantlabs.protobuf.l0.UserBonusReceived")
}

func init() {
	proto.RegisterFile("events/variantlabs/protobuf/l0/user_bonus_received.proto", fileDescriptor_49c3faefd792438e)
}

var fileDescriptor_49c3faefd792438e = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0xce, 0xbd, 0x4a, 0x04, 0x31,
	0x10, 0xc0, 0x71, 0xee, 0x0e, 0x0e, 0x8c, 0x22, 0x9a, 0x42, 0x96, 0x2b, 0x44, 0xac, 0xac, 0x92,
	0x55, 0x1b, 0x4b, 0xf5, 0x11, 0xc2, 0x5a, 0x87, 0xc4, 0x1d, 0x97, 0x40, 0x36, 0x59, 0x32, 0x93,
	0x6d, 0x7d, 0x75, 0xf7, 0x2b, 0x68, 0x65, 0x97, 0x30, 0xfc, 0xe6, 0x3f, 0xec, 0x05, 0x46, 0x08,
	0x84, 0x72, 0x34, 0xc9, 0x99, 0x40, 0xde, 0x58, 0x94, 0x43, 0x8a, 0x14, 0x6d, 0xfe, 0x92, 0xbe,
	0x96, 0x19, 0x21, 0x69, 0x1b, 0x43, 0x46, 0x9d, 0xe0, 0x13, 0xdc, 0x08, 0xad, 0x58, 0xe6, 0xfc,
	0x76, 0x95, 0xe2, 0x8f, 0x14, 0x45, 0x0a, 0x5f, 0x9f, 0x1e, 0xff, 0xdb, 0x9c, 0xc9, 0x79, 0x94,
	0xe4, 0x7a, 0x40, 0x32, 0xfd, 0xb0, 0xc2, 0xfb, 0x6f, 0x76, 0xfd, 0x31, 0xf5, 0xde, 0xe7, 0x9c,
	0xda, 0x6a, 0xfc, 0x8a, 0x1d, 0xb2, 0x6b, 0xab, 0xdd, 0xdd, 0xee, 0xe1, 0x4c, 0xcd, 0x4f, 0xfe,
	0xca, 0x2e, 0xcb, 0x2d, 0xda, 0x90, 0x26, 0xac, 0xf6, 0xd3, 0xf0, 0xfc, 0xe9, 0x24, 0xba, 0x18,
	0x3b, 0x0f, 0xbf, 0x67, 0x34, 0x25, 0xa0, 0x2e, 0x8a, 0x78, 0xa3, 0x06, 0xf9, 0x0d, 0x3b, 0x9a,
	0x3e, 0xe6, 0x40, 0xd5, 0x61, 0x92, 0x7b, 0xb5, 0xfd, 0xec, 0x71, 0x91, 0xcf, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xce, 0xc5, 0xb2, 0x56, 0x16, 0x01, 0x00, 0x00,
}
