// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/variantlabs/protobuf/l0/user_bet_made.proto

package events_variantlabs_protobuf_l0

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserBetMade struct {
	Bid                  string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Uid                  string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Tid                  string                 `protobuf:"bytes,3,opt,name=tid,proto3" json:"tid,omitempty"`
	BetTs                *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=bet_ts,json=betTs,proto3" json:"bet_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserBetMade) Reset()         { *m = UserBetMade{} }
func (m *UserBetMade) String() string { return proto.CompactTextString(m) }
func (*UserBetMade) ProtoMessage()    {}
func (*UserBetMade) Descriptor() ([]byte, []int) {
	return fileDescriptor_0022ed482b654ecd, []int{0}
}

func (m *UserBetMade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBetMade.Unmarshal(m, b)
}
func (m *UserBetMade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBetMade.Marshal(b, m, deterministic)
}
func (m *UserBetMade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBetMade.Merge(m, src)
}
func (m *UserBetMade) XXX_Size() int {
	return xxx_messageInfo_UserBetMade.Size(m)
}
func (m *UserBetMade) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBetMade.DiscardUnknown(m)
}

var xxx_messageInfo_UserBetMade proto.InternalMessageInfo

func (m *UserBetMade) GetBid() string {
	if m != nil {
		return m.Bid
	}
	return ""
}

func (m *UserBetMade) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserBetMade) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *UserBetMade) GetBetTs() *timestamppb.Timestamp {
	if m != nil {
		return m.BetTs
	}
	return nil
}

func init() {
	proto.RegisterType((*UserBetMade)(nil), "events.variantlabs.protobuf.l0.UserBetMade")
}

func init() {
	proto.RegisterFile("events/variantlabs/protobuf/l0/user_bet_made.proto", fileDescriptor_0022ed482b654ecd)
}

var fileDescriptor_0022ed482b654ecd = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x8e, 0xb1, 0x0e, 0x82, 0x30,
	0x14, 0x45, 0x83, 0x28, 0x89, 0x65, 0x31, 0x4c, 0x84, 0xc1, 0x18, 0x27, 0xa7, 0x16, 0xf0, 0x0f,
	0xdc, 0x5d, 0x08, 0xce, 0xa4, 0x0d, 0x4f, 0xd2, 0xa4, 0x50, 0x42, 0x5f, 0xf9, 0x7e, 0x0b, 0x0d,
	0xd1, 0xc9, 0xed, 0xe5, 0xdc, 0x9e, 0xde, 0x4b, 0x4a, 0x98, 0x61, 0x40, 0xc3, 0x66, 0x3e, 0x49,
	0x3e, 0xa0, 0xe2, 0xc2, 0xb0, 0x71, 0xd2, 0xa8, 0x85, 0x7d, 0x33, 0x95, 0x33, 0x6b, 0x60, 0x6a,
	0x04, 0x60, 0xd3, 0xf3, 0x16, 0xe8, 0x9a, 0x24, 0x67, 0xef, 0xd0, 0x1f, 0x87, 0x6e, 0x0e, 0x55,
	0x79, 0x56, 0xfc, 0xfb, 0xd3, 0xa2, 0x54, 0x86, 0xa1, 0xec, 0xc1, 0x20, 0xef, 0x47, 0x2f, 0x5e,
	0x67, 0x12, 0xbf, 0x5c, 0xd3, 0x03, 0xf0, 0xe9, 0x7a, 0x92, 0x13, 0x09, 0x85, 0x6c, 0xd3, 0xe0,
	0x12, 0xdc, 0x8e, 0xd5, 0x72, 0x2e, 0xc4, 0x3a, 0xb2, 0xf3, 0xc4, 0x7a, 0x82, 0x8e, 0x84, 0x9e,
	0xb8, 0x33, 0x29, 0x48, 0xb4, 0x2c, 0x45, 0x93, 0xee, 0x1d, 0x8c, 0xcb, 0x8c, 0x76, 0x5a, 0x77,
	0x0a, 0xbe, 0xe3, 0xea, 0xad, 0xb6, 0x3a, 0xb8, 0x97, 0xb5, 0x11, 0xd1, 0x1a, 0xdd, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x25, 0xf0, 0x08, 0xf9, 0x07, 0x01, 0x00, 0x00,
}
