// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/variantlabs/protobuf/l0/user_money_deposited.proto

package events_variantlabs_protobuf_l0

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMoneyDeposited struct {
	Uid                  string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DepositedTs          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deposited_ts,json=depositedTs,proto3" json:"deposited_ts,omitempty"`
	Amount               float32                `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserMoneyDeposited) Reset()         { *m = UserMoneyDeposited{} }
func (m *UserMoneyDeposited) String() string { return proto.CompactTextString(m) }
func (*UserMoneyDeposited) ProtoMessage()    {}
func (*UserMoneyDeposited) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce6075b6e51a6cf, []int{0}
}

func (m *UserMoneyDeposited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMoneyDeposited.Unmarshal(m, b)
}
func (m *UserMoneyDeposited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMoneyDeposited.Marshal(b, m, deterministic)
}
func (m *UserMoneyDeposited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMoneyDeposited.Merge(m, src)
}
func (m *UserMoneyDeposited) XXX_Size() int {
	return xxx_messageInfo_UserMoneyDeposited.Size(m)
}
func (m *UserMoneyDeposited) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMoneyDeposited.DiscardUnknown(m)
}

var xxx_messageInfo_UserMoneyDeposited proto.InternalMessageInfo

func (m *UserMoneyDeposited) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserMoneyDeposited) GetDepositedTs() *timestamppb.Timestamp {
	if m != nil {
		return m.DepositedTs
	}
	return nil
}

func (m *UserMoneyDeposited) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*UserMoneyDeposited)(nil), "events.variantlabs.protobuf.l0.UserMoneyDeposited")
}

func init() {
	proto.RegisterFile("events/variantlabs/protobuf/l0/user_money_deposited.proto", fileDescriptor_fce6075b6e51a6cf)
}

var fileDescriptor_fce6075b6e51a6cf = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xb2, 0x4c, 0x2d, 0x4b, 0xcd,
	0x2b, 0x29, 0xd6, 0x2f, 0x4b, 0x2c, 0xca, 0x4c, 0xcc, 0x2b, 0xc9, 0x49, 0x4c, 0x2a, 0xd6, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0xcf, 0x31, 0xd0, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a,
	0xcf, 0xcd, 0xcf, 0x4b, 0xad, 0x8c, 0x4f, 0x49, 0x2d, 0xc8, 0x2f, 0xce, 0x2c, 0x49, 0x4d, 0xd1,
	0x03, 0x2b, 0x10, 0x92, 0x83, 0x68, 0xd5, 0x43, 0xd2, 0xaa, 0x07, 0xd3, 0xaa, 0x97, 0x63, 0x20,
	0x65, 0x88, 0xcf, 0xe8, 0xd2, 0x92, 0xcc, 0x9c, 0x62, 0xfd, 0x92, 0xcc, 0xdc, 0xd4, 0xe2, 0x92,
	0xc4, 0xdc, 0x02, 0x88, 0x46, 0xa5, 0x5a, 0x2e, 0xa1, 0x50, 0xa0, 0x85, 0xbe, 0x20, 0xfb, 0x5c,
	0x60, 0xd6, 0x09, 0x09, 0x70, 0x31, 0x97, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x81, 0x98, 0x42, 0xb6, 0x5c, 0x3c, 0x70, 0xd7, 0xc4, 0x97, 0x14, 0x4b, 0x30, 0x01, 0xa5, 0xb8,
	0x8d, 0xa4, 0xf4, 0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0x11, 0xae, 0x08, 0x81, 0x99, 0x1f, 0xc4,
	0x0d, 0x57, 0x1f, 0x52, 0x2c, 0x24, 0xc6, 0xc5, 0x96, 0x98, 0x9b, 0x5f, 0x9a, 0x57, 0x22, 0xc1,
	0x0c, 0xd4, 0xc8, 0x14, 0x04, 0xe5, 0x25, 0xb1, 0x81, 0x35, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xd7, 0x97, 0xde, 0xe3, 0x15, 0x01, 0x00, 0x00,
}
