// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/variantlabs/protobuf/l0/user_table_started.proto

package events_variantlabs_protobuf_l0

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserTableStarted struct {
	Uid                  string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tid                  string                 `protobuf:"bytes,2,opt,name=tid,proto3" json:"tid,omitempty"`
	StartedAtTs          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at_ts,json=startedAtTs,proto3" json:"started_at_ts,omitempty"`
	Players              []string               `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserTableStarted) Reset()         { *m = UserTableStarted{} }
func (m *UserTableStarted) String() string { return proto.CompactTextString(m) }
func (*UserTableStarted) ProtoMessage()    {}
func (*UserTableStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc297c954759439, []int{0}
}

func (m *UserTableStarted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTableStarted.Unmarshal(m, b)
}
func (m *UserTableStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTableStarted.Marshal(b, m, deterministic)
}
func (m *UserTableStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTableStarted.Merge(m, src)
}
func (m *UserTableStarted) XXX_Size() int {
	return xxx_messageInfo_UserTableStarted.Size(m)
}
func (m *UserTableStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTableStarted.DiscardUnknown(m)
}

var xxx_messageInfo_UserTableStarted proto.InternalMessageInfo

func (m *UserTableStarted) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserTableStarted) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *UserTableStarted) GetStartedAtTs() *timestamppb.Timestamp {
	if m != nil {
		return m.StartedAtTs
	}
	return nil
}

func (m *UserTableStarted) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func init() {
	proto.RegisterType((*UserTableStarted)(nil), "events.variantlabs.protobuf.l0.UserTableStarted")
}

func init() {
	proto.RegisterFile("events/variantlabs/protobuf/l0/user_table_started.proto", fileDescriptor_2bc297c954759439)
}

var fileDescriptor_2bc297c954759439 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x8e, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0x15, 0xc5, 0x2c, 0xc2, 0x92, 0x53, 0xd8, 0x83, 0x2c, 0x9e, 0x3c, 0x25, 0xab,
	0x1e, 0xbc, 0x09, 0xbe, 0xc2, 0x5a, 0xcf, 0x21, 0xa1, 0x63, 0x09, 0xa4, 0x4d, 0xc9, 0x4c, 0x0a,
	0xbe, 0x85, 0x8f, 0x6c, 0xda, 0xb4, 0xe8, 0xc9, 0xdb, 0xcc, 0x3f, 0x7c, 0xff, 0x37, 0xec, 0x05,
	0x26, 0x18, 0x08, 0xd5, 0x64, 0xa2, 0x33, 0x03, 0x79, 0x63, 0x51, 0x8d, 0x31, 0x50, 0xb0, 0xe9,
	0x53, 0xf9, 0x93, 0x4a, 0x08, 0x51, 0x93, 0xb1, 0x1e, 0x34, 0x92, 0x89, 0x04, 0xad, 0x5c, 0xce,
	0xfc, 0xae, 0x80, 0xf2, 0x0f, 0x28, 0x37, 0x50, 0xfa, 0xd3, 0xe1, 0xf1, 0xbf, 0xe2, 0x44, 0xce,
	0xa3, 0x22, 0xd7, 0x43, 0x2e, 0xed, 0xc7, 0x02, 0xde, 0x7f, 0x57, 0x6c, 0xff, 0x91, 0x7d, 0xcd,
	0xac, 0x7b, 0x2f, 0x36, 0xbe, 0x67, 0x75, 0x72, 0xad, 0xa8, 0x8e, 0xd5, 0xc3, 0xcd, 0x79, 0x1e,
	0xe7, 0x84, 0x72, 0x72, 0x51, 0x92, 0x3c, 0xf2, 0x57, 0x76, 0xbb, 0x3e, 0xa7, 0x0d, 0x69, 0x42,
	0x51, 0xe7, 0xdb, 0xee, 0xe9, 0x20, 0xbb, 0x10, 0x3a, 0x0f, 0xbf, 0x7f, 0x35, 0x9b, 0xf1, 0xbc,
	0x5b, 0x81, 0x37, 0x6a, 0x90, 0x0b, 0x76, 0x3d, 0x7a, 0xf3, 0x05, 0x11, 0xc5, 0xe5, 0xb1, 0xce,
	0xad, 0xdb, 0x6a, 0xaf, 0x16, 0xf4, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xa5, 0xda, 0xa9,
	0x27, 0x01, 0x00, 0x00,
}
