// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_bet_made.proto

package v1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserBetMade struct {
	Bid                  string               `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Uid                  string               `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Tid                  string               `protobuf:"bytes,3,opt,name=tid,proto3" json:"tid,omitempty"`
	BetTs                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=bet_ts,json=betTs,proto3" json:"bet_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserBetMade) Reset()         { *m = UserBetMade{} }
func (m *UserBetMade) String() string { return proto.CompactTextString(m) }
func (*UserBetMade) ProtoMessage()    {}
func (*UserBetMade) Descriptor() ([]byte, []int) {
	return fileDescriptor_384dcf124fe03e65, []int{0}
}

func (m *UserBetMade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBetMade.Unmarshal(m, b)
}
func (m *UserBetMade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBetMade.Marshal(b, m, deterministic)
}
func (m *UserBetMade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBetMade.Merge(m, src)
}
func (m *UserBetMade) XXX_Size() int {
	return xxx_messageInfo_UserBetMade.Size(m)
}
func (m *UserBetMade) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBetMade.DiscardUnknown(m)
}

var xxx_messageInfo_UserBetMade proto.InternalMessageInfo

func (m *UserBetMade) GetBid() string {
	if m != nil {
		return m.Bid
	}
	return ""
}

func (m *UserBetMade) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserBetMade) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *UserBetMade) GetBetTs() *timestamp.Timestamp {
	if m != nil {
		return m.BetTs
	}
	return nil
}

func init() {
	proto.RegisterType((*UserBetMade)(nil), "v1.UserBetMade")
}

func init() {
	proto.RegisterFile("user_bet_made.proto", fileDescriptor_384dcf124fe03e65)
}

var fileDescriptor_384dcf124fe03e65 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2d, 0x4e, 0x2d,
	0x8a, 0x4f, 0x4a, 0x2d, 0x89, 0xcf, 0x4d, 0x4c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2a, 0x33, 0x94, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x24, 0x95,
	0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x14, 0x29, 0x95, 0x71,
	0x71, 0x87, 0x02, 0xf5, 0x3a, 0xa5, 0x96, 0xf8, 0x02, 0x75, 0x0a, 0x09, 0x70, 0x31, 0x27, 0x65,
	0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x20, 0x91, 0x52, 0xa0, 0x08, 0x13,
	0x44, 0xa4, 0x14, 0x22, 0x52, 0x02, 0x14, 0x61, 0x86, 0x88, 0x00, 0x99, 0x42, 0x86, 0x5c, 0x6c,
	0x20, 0xbb, 0x4b, 0x8a, 0x25, 0x58, 0x80, 0x82, 0xdc, 0x46, 0x52, 0x7a, 0x10, 0x6b, 0xf5, 0x60,
	0xd6, 0xea, 0x85, 0xc0, 0xac, 0x0d, 0x62, 0x05, 0xaa, 0x0c, 0x29, 0x4e, 0x62, 0x03, 0x4b, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x3c, 0xbd, 0x23, 0xba, 0x00, 0x00, 0x00,
}
