// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_logged_in.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserLoggedIn struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	LoggedAtTs           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=logged_at_ts,json=loggedAtTs,proto3" json:"logged_at_ts,omitempty"`
	Ip                   string               `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Country              string               `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Latitude             float32              `protobuf:"fixed32,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32              `protobuf:"fixed32,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserLoggedIn) Reset()         { *m = UserLoggedIn{} }
func (m *UserLoggedIn) String() string { return proto.CompactTextString(m) }
func (*UserLoggedIn) ProtoMessage()    {}
func (*UserLoggedIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_b76add4045859ce2, []int{0}
}

func (m *UserLoggedIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoggedIn.Unmarshal(m, b)
}
func (m *UserLoggedIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoggedIn.Marshal(b, m, deterministic)
}
func (m *UserLoggedIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoggedIn.Merge(m, src)
}
func (m *UserLoggedIn) XXX_Size() int {
	return xxx_messageInfo_UserLoggedIn.Size(m)
}
func (m *UserLoggedIn) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoggedIn.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoggedIn proto.InternalMessageInfo

func (m *UserLoggedIn) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserLoggedIn) GetLoggedAtTs() *timestamp.Timestamp {
	if m != nil {
		return m.LoggedAtTs
	}
	return nil
}

func (m *UserLoggedIn) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *UserLoggedIn) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *UserLoggedIn) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *UserLoggedIn) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*UserLoggedIn)(nil), "v1.UserLoggedIn")
}

func init() {
	proto.RegisterFile("user_logged_in.proto", fileDescriptor_b76add4045859ce2)
}

var fileDescriptor_b76add4045859ce2 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x2d, 0x4e, 0x2d,
	0x8a, 0xcf, 0xc9, 0x4f, 0x4f, 0x4f, 0x4d, 0x89, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2a, 0x33, 0x94, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x24,
	0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x14, 0x29, 0x1d,
	0x62, 0xe4, 0xe2, 0x09, 0x05, 0xea, 0xf6, 0x01, 0x6b, 0xf6, 0xcc, 0x13, 0x12, 0xe0, 0x62, 0x2e,
	0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0x6c, 0xb8, 0x78, 0xa0,
	0x46, 0x27, 0x96, 0xc4, 0x97, 0x14, 0x4b, 0x30, 0x01, 0xa5, 0xb8, 0x8d, 0xa4, 0xf4, 0x20, 0x46,
	0xeb, 0xc1, 0x8c, 0xd6, 0x0b, 0x81, 0x19, 0x1d, 0xc4, 0x05, 0x51, 0xef, 0x58, 0x12, 0x52, 0x2c,
	0xc4, 0xc7, 0xc5, 0x94, 0x59, 0x20, 0xc1, 0x0c, 0x36, 0x0e, 0xc8, 0x12, 0x92, 0xe0, 0x62, 0x4f,
	0xce, 0x2f, 0xcd, 0x2b, 0x29, 0xaa, 0x94, 0x60, 0x01, 0x0b, 0xc2, 0xb8, 0x42, 0x52, 0x5c, 0x1c,
	0x39, 0x89, 0x25, 0x99, 0x25, 0xa5, 0x29, 0xa9, 0x12, 0xac, 0x40, 0x29, 0xa6, 0x20, 0x38, 0x5f,
	0x48, 0x86, 0x8b, 0x33, 0x27, 0x3f, 0x2f, 0x1d, 0x22, 0xc9, 0x06, 0x96, 0x44, 0x08, 0x24, 0xb1,
	0x81, 0xdd, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x1e, 0x14, 0xe4, 0x08, 0x01, 0x00,
	0x00,
}
