// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_money_deposited.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMoneyDeposited struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DepositedTs          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=deposited_ts,json=depositedTs,proto3" json:"deposited_ts,omitempty"`
	Amount               float32              `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserMoneyDeposited) Reset()         { *m = UserMoneyDeposited{} }
func (m *UserMoneyDeposited) String() string { return proto.CompactTextString(m) }
func (*UserMoneyDeposited) ProtoMessage()    {}
func (*UserMoneyDeposited) Descriptor() ([]byte, []int) {
	return fileDescriptor_c52520178f5c0b89, []int{0}
}

func (m *UserMoneyDeposited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMoneyDeposited.Unmarshal(m, b)
}
func (m *UserMoneyDeposited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMoneyDeposited.Marshal(b, m, deterministic)
}
func (m *UserMoneyDeposited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMoneyDeposited.Merge(m, src)
}
func (m *UserMoneyDeposited) XXX_Size() int {
	return xxx_messageInfo_UserMoneyDeposited.Size(m)
}
func (m *UserMoneyDeposited) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMoneyDeposited.DiscardUnknown(m)
}

var xxx_messageInfo_UserMoneyDeposited proto.InternalMessageInfo

func (m *UserMoneyDeposited) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserMoneyDeposited) GetDepositedTs() *timestamp.Timestamp {
	if m != nil {
		return m.DepositedTs
	}
	return nil
}

func (m *UserMoneyDeposited) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*UserMoneyDeposited)(nil), "v1.UserMoneyDeposited")
}

func init() {
	proto.RegisterFile("user_money_deposited.proto", fileDescriptor_c52520178f5c0b89)
}

var fileDescriptor_c52520178f5c0b89 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x2d, 0x4e, 0x2d,
	0x8a, 0xcf, 0xcd, 0xcf, 0x4b, 0xad, 0x8c, 0x4f, 0x49, 0x2d, 0xc8, 0x2f, 0xce, 0x2c, 0x49, 0x4d,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x94, 0x92, 0x4f, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x24, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24,
	0xe6, 0x16, 0x40, 0x14, 0x29, 0xd5, 0x72, 0x09, 0x85, 0x02, 0x8d, 0xf0, 0x05, 0x99, 0xe0, 0x02,
	0x33, 0x40, 0x48, 0x80, 0x8b, 0xb9, 0x34, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08,
	0xc4, 0x14, 0xb2, 0xe5, 0xe2, 0x81, 0x9b, 0x1f, 0x5f, 0x52, 0x2c, 0xc1, 0x04, 0x94, 0xe2, 0x36,
	0x92, 0xd2, 0x83, 0x98, 0xaf, 0x07, 0x33, 0x5f, 0x2f, 0x04, 0x66, 0x7e, 0x10, 0x37, 0x5c, 0x7d,
	0x48, 0xb1, 0x90, 0x18, 0x17, 0x5b, 0x62, 0x6e, 0x7e, 0x69, 0x5e, 0x89, 0x04, 0x33, 0x50, 0x23,
	0x53, 0x10, 0x94, 0x97, 0xc4, 0x06, 0xd6, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xbb,
	0x7b, 0x4c, 0xc8, 0x00, 0x00, 0x00,
}
